# Generated by Django 3.1.3 on 2021-01-09 21:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, '공부'), (1, '문화/예술'), (2, '운동'), (3, '자기관리'), (4, '집안일'), (5, '게임'), (6, '유투브'), (7, '인터넷'), (8, '기타'), (9, '수업'), (10, '퀘스트')], default=0, verbose_name='카테고리')),
                ('name', models.CharField(max_length=100, verbose_name='행동이름')),
                ('xp', models.IntegerField(default=0, verbose_name='경험치')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='시간')),
                ('date', models.DateField(auto_created=True, default=datetime.date.today, verbose_name='날짜')),
                ('memo', models.CharField(blank=True, default='', max_length=60, verbose_name='추가설명')),
                ('repeat', models.IntegerField(default=1, verbose_name='반복 횟수')),
                ('xp', models.IntegerField(default=0, verbose_name='경험치')),
                ('checked', models.BooleanField(default=False, verbose_name='확인')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, '공부'), (1, '문화/예술'), (2, '운동'), (3, '자기관리'), (4, '집안일'), (5, '게임'), (6, '유투브'), (7, '인터넷'), (8, '기타'), (9, '수업'), (10, '퀘스트')], default=0, verbose_name='카테고리')),
                ('name', models.CharField(max_length=100, verbose_name='퀘스트 이름')),
                ('desc', models.TextField(null=True, verbose_name='퀘스트 내용')),
                ('xp', models.IntegerField(default=0, verbose_name='경험치')),
                ('accomplishment', models.BooleanField(default=False, verbose_name='수행 여부')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='수행자')),
            ],
        ),
    ]
