# Generated by Django 3.1.3 on 2020-11-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.CharField(default=0, max_length=100, verbose_name='카테고리'),
            preserve_default=False,
        ),
    ]
