# Generated by Django 3.1.3 on 2020-11-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_action_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.IntegerField(choices=[(0, '공부'), (1, '문화/예술'), (2, '운동'), (3, '자기관리'), (4, '집안일')], default=0, verbose_name='카테고리'),
        ),
    ]
