# Generated by Django 3.1.3 on 2020-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20201112_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='memo',
            field=models.CharField(default=' ', max_length=10, verbose_name='추가설명'),
        ),
    ]
