# Generated by Django 3.1.3 on 2020-11-12 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_record_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.date.today, verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.CharField(default='', max_length=10, verbose_name='추가설명'),
        ),
    ]
