# Generated by Django 3.1.3 on 2020-11-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_record_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='추가설명'),
        ),
    ]
