# Generated by Django 3.1.3 on 2020-11-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0009_record_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.IntegerField(choices=[(0, '공부'), (1, '문화/예술'), (2, '운동'), (3, '자기관리'), (4, '집안일'), (5, '게임'), (6, '유투브'), (7, '인터넷'), (8, '기타'), (9, '수업'), (10, '퀘스트')], default=0, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='추가설명'),
        ),
    ]
