# Generated by Django 3.1.3 on 2020-11-18 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quest', '0010_auto_20201119_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, '공부'), (1, '문화/예술'), (2, '운동'), (3, '자기관리'), (4, '집안일'), (5, '게임'), (6, '유투브'), (7, '인터넷'), (8, '기타'), (9, '수업'), (10, '퀘스트')], default=0, verbose_name='카테고리')),
                ('name', models.CharField(max_length=100, verbose_name='퀘스트 이름')),
                ('desc', models.TextField(null=True, verbose_name='퀘스트 내용')),
                ('xp', models.IntegerField(default=0, verbose_name='경험치')),
                ('accomplishment', models.BooleanField(default=False, verbose_name='수행 여부')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
