# Generated by Django 3.1.3 on 2020-11-21 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quest', '0011_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='확인'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='수행자'),
        ),
    ]
